[package]

name = "rust-telnet-client"
version = "0.0.1"
authors = ["Jonathan Castello <twisolar@gmail.com>"]

[dependencies.rust-telnet]
git = "https://github.com/Nercury/rust-telnet.git"
rev = "a1b5c532cad01c26458d99667eda9429ae188e56"
